api/urls.py
from django.urls import path
from api.views import *

# user
urlpatterns = [
    path('users/register/', register, name='register'),
    path('users/login/', login, name='login'),
    path('users/get/', get_users, name='get_users'),
    path('users/delete/<int:pk>/', delete_user, name='delete_user'),
    path('users/update/<int:pk>/', update_user, name='update_user'),

    path('users/status/', get_user_status, name='get_user_status')
]

# answer
urlpatterns += [
    path('answer/get', get_answer, name='get_answer'),
    path('answer/add', add_answer, name='add_answer'),
    path('answer/update', update_answer, name='update_answer'),
    path('answer/delete', delete_answer, name='delete_answer'),

    path('answer/statistics', statistics_get, name='statistics_get'),
    path('answer/process', process_get, name='process_get')
]

onlineChat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from onlineChat import settings
from user.views import CustomLoginView, index

# 管理台
urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 首页
urlpatterns += [
    path('index/', index, name='index'),
    path('', RedirectView.as_view(url='/index')),
]

# api
urlpatterns += [
    path('api/', include('api.urls')),
]

# 内置登陆
urlpatterns += [
    path('accounts/login/', CustomLoginView.as_view(), name='login'),  # 使用自定义登录视图
    path('accounts/', include('django.contrib.auth.urls')),  # 提供了一组默认的 URL 模式
    # /accounts/login/：用户登录视图。--LoginView
    # /accounts/logout/：用户注销视图。--LogoutView
    # ······
]

urlpatterns += [
    path('user/', include('user.urls')),
    path('answer/', include('answer.urls')),
    path('backend/', include('backend.urls')),
]

answer/forms.py
from django import forms


class KeywordForm(forms.Form):
    keywords = forms.CharField(label='关键词', max_length=255, help_text='输入1~3个关键词，用逗号隔开')

templates/answer_add.html
{% extends 'index.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data" action="{% url 'answer_add' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <script>
        function toggleFields() {
            const responseType = document.getElementById('id_response_type').value;
            const contentField = document.getElementById('id_content').parentElement;
            const imageField = document.getElementById('id_image').parentElement;

            if (responseType === 'image') {
                contentField.style.display = 'none';
                imageField.style.display = 'block';
            } else {
                contentField.style.display = 'block';
                imageField.style.display = 'none';
            }
        }

        window.onload = function() {
            toggleFields();
            document.getElementById('id_response_type').addEventListener('change', toggleFields);
        }
    </script>
{% endblock %}

templates/answer_admin.html
{% extends 'index.html' %}
{% block content %}
     <h1>应答管理</h1>
    <div class="sidebar-nav">
    <a href="{% url 'answer_add' %}">添加</a>
    </div>
    <br>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Keywords</th>
                <th>Response Type</th>
                <th>Content</th>
                <th>AI Answer</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for answer in answers %}
            <tr>
                <td>{{ answer.id }}</td>
                <td>{{ answer.keywords }}</td>
                <td>{{ answer.response_type }}</td>
                <td>{{ answer.content }}</td>
                <td>{{ answer.ai_answer }}</td>
                <td>
                    <a href="{% url 'answer_edit' answer.id %}">编辑</a>
                    <form action="{% url 'answer_delete' answer.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit">删除</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/answer_edit.html
{% extends 'index.html' %}
{% block content %}
     <h1>Edit Answer</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/chat.html
{% extends 'index.html' %}
{% block content %}
    <div id="chat-container">
        <h2>聊天室</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button id="sendButton" type="submit">发送</button>
        </form>
        <div id="messages">
            {% if answer %}
                {% for data in answer %}
                    {% if data.ai_answer %}
                        <h4>暂无数据，调用AI回答：</h4>
                    {% endif %}
                    {% if data.response_type == 'text' %}
                        <p>{{ data.content }}<br></p>
                    {% elif data.response_type == 'image' %}
                        <img src="{{ data.content }}" alt="images">
                    {% elif data.response_type == 'link' %}
                        <a href="http://{{ data.content }}" target="_blank">{{ data.content }}<br></a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>

        <form id="uploadForm" method="post" style="display: none;" enctype="multipart/form-data" action="{% url 'addlogo' %}">
            {% csrf_token %}
            <input type="file" name="file">
            <button type="submit">下载加水印的图片</button>
        </form>

        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var keywordsField = document.querySelector('#id_keywords');
            var sendButton = document.querySelector('#sendButton');
            var messages = document.querySelector('#messages')

            keywordsField.addEventListener('input', function() {
                var keywords = keywordsField.value.split(',');
                var allowedKeywords = ['噢易', 'oseasy', 'os-easy', 'logo', '水印'];

                var showUploadForm = false;
                var showSendButton = true;
                var showMessages = true;
                for (var i = 0; i < keywords.length; i++) {
                    if (allowedKeywords.includes(keywords[i].trim())) {
                        showUploadForm = true;
                        showSendButton = false;
                        showMessages = false;
                        break;
                    }
                }

                var uploadForm = document.getElementById('uploadForm');
                uploadForm.style.display = showUploadForm ? 'block' : 'none';
                sendButton.style.display = showSendButton ? 'block' : 'none';
                messages.style.display = showMessages ? 'block' : 'none';
            });
        });

    </script>
{% endblock %}

templates/chat_room.html
{% extends 'index.html' %}
{% block content %}
    <div id="messages" style="height: 70vh">
        <div id="chat-log"></div>
    </div>
    <form id="chat-message-form">
        <input type="text" id="chat-message-input" autocomplete="off">
        <button type="submit">Send</button>
    </form>
    <br>
    <form id="chat-file-form" enctype="multipart/form-data">
        <p style="margin-bottom: 0px;">可发送图片或视频</p>
        <input type="file" id="chat-file-input">
        <button type="submit">Upload</button>
    </form>
    <a id="download-link" style="display:none;"></a>

    <script>
        const roomName = "{{ room_name }}";
        const userPhoneNumber = "{{ user.phone_number }}";
        const chatSocket = new WebSocket(
            'ws://' + window.location.host + '/ws/chat/' + roomName + '/');

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const message = data.message;
            const messageType = data.message_type;
            const fileType = data.file_type;

            const chatLog = document.querySelector('#chat-log');
            const messageElement = document.createElement('div');

            if (messageType === 'file') {
                if (fileType.startsWith('image/')) {
                    const img = document.createElement('img');
                    img.src = message;
                    messageElement.appendChild(img);
                } else if (fileType.startsWith('video/')) {
                    const video = document.createElement('video');
                    video.src = message;
                    video.controls = true;
                    messageElement.appendChild(video);
                } else if (fileType.startsWith('audio/')) {
                    const audio = document.createElement('audio');
                    audio.src = message;
                    audio.controls = true;
                    messageElement.appendChild(audio);
                } else {
                    const link = document.createElement('a');
                    link.href = message;
                    link.innerText = '下载文档';
                    link.download = '';
                    messageElement.appendChild(link);
                }
            } else {
                messageElement.innerText = message;
            }

            const userElement = document.createElement('h4');
            userElement.innerText = data.user_phone_number+':';
            chatLog.appendChild(userElement);

            chatLog.appendChild(messageElement);
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-form').onsubmit = function(e) {
            e.preventDefault();
            const messageInput = document.querySelector('#chat-message-input');
            const message = messageInput.value;
            chatSocket.send(JSON.stringify({
                'type': 'text',
                'message': message,
                'user_phone_number': userPhoneNumber
            }));
            messageInput.value = '';
        };

        document.querySelector('#chat-file-form').onsubmit = function(e) {
            e.preventDefault();
            const fileInput = document.querySelector('#chat-file-input');
            const file = fileInput.files[0];
            const reader = new FileReader();
            reader.onload = function(event) {
                chatSocket.send(JSON.stringify({
                    'type': 'file',
                    'file_data': {
                        'name': file.name,
                        'data': event.target.result,
                    },
                    'file_type': file.type,
                    'user_phone_number': userPhoneNumber
                }));
            };
            reader.readAsDataURL(file);
        };
    </script>
{% endblock %}

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% block title %}<title>CHAT</title>{% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                {% if user.is_authenticated %}
                    <li>欢迎: {{ user.get_username }}</li>
                    <li>
                    {% csrf_token %}
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link" style="font-size: 20px;">登出</button>
                    </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'login'%}">登录</a></li>
                {% endif %}
                </ul>

                <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">首页</a></li>
                </ul>

                {% if user.is_staff %}
                    <hr>
                    <ul class="sidebar-nav">
                    <li>功能</li>
                    <li><a href="{% url 'chat' %}">聊天室</a></li>
                    <li><a href="{% url 'user_online' %}">私信</a></li>
                    <br>
                    <li>管理</li>
                    <li><a href="{% url 'answer_admin' %}">应答管理</a></li>
                    <li><a href="{% url 'user_admin' %}">用户管理</a></li>
                    <li><a href="{% url 'statistics_admin' %}">数据统计</a></li>
                    </ul>
                {% endif %}
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %}
                <h2>⬅选择左侧功能</h2>
            {% endblock %}
        </div>
{#    分页#}
{#        <div class="col-sm-10 ">#}
{#        {% block pagination %}#}
{#            {% if is_paginated %}#}
{#                <div class="pagination">#}
{#                <span class="page-links">#}
{#                {% if page_obj.has_previous %}#}
{#                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>#}
{#                {% endif %}#}
{#                <span class="page-current">#}
{#                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{#                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>#}
{#                {% endif %}#}
{#                </span>#}
{#                </div>#}
{#            {% endif %}#}
{#        {% endblock %}#}
{#        </div>#}
    </div>
</div>
</body>
</html>

templates/login.html
{% extends 'index.html' %}
{% block content %}
    <h2>登录</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">登录</button>
    </form>
    <p>还没有账号？ <a href="{% url 'register_page' %}">注册</a></p>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/register.html
{% extends 'index.html' %}
{% block content %}
    <h2>注册</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">注册</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/statistics_admin.html
{% extends 'index.html' %}
{% block content %}
    <h1>数据统计</h1>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>IP</th>
            <th>BROWSER TYPE</th>
            <th>KEYWORD</th>
            <th>TIME</th>
        </tr>
        {% for data in response %}
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.ip_address }}</td>
                <td>{{ data.browser_type }}</td>
                <td>{{ data.keyword }}</td>
                <td>{{ data.timestamp }}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="sidebar-nav">
        <li><a href="{% url 'data_excel' %}">导出统计数据为 Excel</a></li>
        <li><a href="{% url 'data_image' %}">导出统计数据为 图片</a></li>
    </div>

{% endblock %}

templates/user_admin.html
{% extends 'index.html' %}
{% block content %}
    <h1>用户管理</h1>
    <div class="sidebar-nav">
    <li><a href="{% url 'user_export' %}">导出用户数据</a></li>
    <br>
    <form method="post" enctype="multipart/form-data" action="{% url 'user_import' %}">
        {% csrf_token %}
        <input type="file" name="file" id="fileInput">
        <button type="submit">导入用户数据</button>
    </form>
    </div>
    <br>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Status</th>
            <th>操作</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.phone_number }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.status }}</td>
            <td>
                <a href="{% url 'user_edit' user.id %}">修改</a>
                <form method="post" action="{% url 'user_delete' user.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">删除</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div class="sidebar-nav">
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

templates/user_chat.html
{% extends 'index.html' %}
{% block content %}
    <h1>与用户{{ other_user.phone_number }}私信</h1>
    <a href="">刷新消息列表</a>
    <div>
        {% for message in messages %}
            <div>
                {{ message.timestamp | date:"Y-m-d H:i" }}&emsp;
                <strong>{{ message.sender.phone_number }}：</strong>{{ message.content }}
            </div>
        {% endfor %}
    </div>
    <form method="post">
        {% csrf_token %}
        <textarea name="content" required></textarea>
        <button type="submit">发送</button>
    </form>
{% endblock %}

templates/user_edit.html
{% extends 'index.html' %}
{% block content %}
     <h1>修改用户信息</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">提交</button>
    </form>
{% endblock %}

templates/user_online.html
{% extends 'index.html' %}
{% block content %}
    <h1>在线用户</h1>
    <h4>私信-新:Channel+WebSocket+Redis</h4>
    <h4>私信-旧:存数据取数据</h4>
    <div class="sidebar-nav">
        {% for data in userstatus %}
            {% if user.phone_number not in data.phone_number %}
                {% if data.is_online %}
                    <span class="online">●</span>
                    {{ data.phone_number }} - {{ data.ip_address }}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'chat_room' room_name=user.phone_number|add:data.phone_number %}">私信-新</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'userchat' data.user %}">私信-旧</a>
                    <br>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <h1>离线用户</h1>
    <div class="sidebar-nav">
        {% for data in userstatus %}
            {% if user.phone_number not in data.phone_number %}
                {% if  not data.is_online%}
                    <span class="offline">●</span>
                        {{ data.phone_number }}
                    <br>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}